### ISSUE TITLE
WHY NOT GIVING HACKTOBER FEST LABEL WHEN MERGE PR ?

### ISSUE THREAD

**Issue by Rjndrkha** [Im-Soumya/Hacktoberfest_2022#15]

**Comment by Rjndrkha** [comment]
[](https://github.com/Rjndrkha/Data-Structure_Code-Programm/pulls?q=is%3Apr+is%3Aclosed)

Please see this repo , if u are a maintener when merge PR add Hacktoberfest label !

**Comment by Im-Soumya** [comment]
Please check and let me know is it fine now?
I mean that's how it should be right?

**Comment by Rjndrkha** [comment]
![image](https://user-images.githubusercontent.com/75615789/196391880-bbb7815b-53eb-4ab1-b669-023ab557dca2.png)

Please See The rules Below !
https://hacktoberfest.com/participation/

**Comment by Rjndrkha** [comment]
thankyou
