### ISSUE TITLE
Request to Contribute for Python-MachineLearning

### ISSUE THREAD

**Issue by Maria-Ahmed** [Im-Soumya/Hacktoberfest_2022#29]
Hi,

I am newbie in open-source. While learning python which is used for Machine learning and Data Science. I compiled a series of jupyter notebook files for each topic.

Can i just contribute directly by opening up the PR? Or will the maintainers assign it to me first?

**Comment by Im-Soumya** [comment]
You can contribute directly, no issues. Just a create a separate folder for it, that's it.

**Comment by Maria-Ahmed** [comment]
Thanks, have added it. Waiting for you to merge!
